//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch.Face.Scroll.Properties
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("Watch.Face.Scroll.Properties.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Resources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            OldEnglish11 = -16243,
            OldEnglish09 = -11971,
            OldEnglish14 = -9499,
            OldEnglish08 = -7694,
            OldEnglish18 = -7693,
            OldEnglish16 = -2422,
            OldEnglish06 = -2421,
            OldEnglish10 = 14223,
            OldEnglish20 = 14224,
            OldEnglish05 = 14416,
            digital = 15780,
            OldEnglish12 = 21864,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            scroll = 10168,
        }
    }
}
